apiVersion: v1
kind: Secret
metadata:
  name: tarnished-api-secrets
  labels:
    app: tarnished-api
type: Opaque
data:
  # Base64 encoded values - update these with actual secrets
  # To encode: echo -n "your-secret-value" | base64
  
  # HMAC secret for request signing (base64 encoded)
  # Default: "change-me-in-production"
  hmac-secret: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
  
  # New Relic license key (base64 encoded)  
  # Replace with actual key: echo -n "your-license-key" | base64
  new-relic-license-key: ""
  
  # New Relic account ID (base64 encoded)
  # Replace with actual account ID: echo -n "your-account-id" | base64
  new-relic-account-id: ""