name: "Timed Step With New Relic"
description: "Run a command and report its duration to New Relic"
inputs:
  step:
    description: "The name of the step being timed"
    required: true
  command:
    description: "The command to run and time"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Timed Command
      shell: bash
      run: |
        if ! command -v jq &> /dev/null; then
          echo "jq is required but not installed. Skipping New Relic reporting."
          # Still run the command even if jq is missing
          exec bash -c "${{ inputs.command }}"
        fi

        start_time=$(date +%s)
        
        # Run the command with error handling
        set +e
        bash -c "${{ inputs.command }}"
        exit_code=$?
        set -e
        
        end_time=$(date +%s)
        duration=$((end_time - start_time))
        timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

        pr_number=$(jq -r '.pull_request.number // empty' "$GITHUB_EVENT_PATH")
        commit_message=$(jq -r '.head_commit.message // .pull_request.title // empty' "$GITHUB_EVENT_PATH")

        if [ $exit_code -eq 0 ]; then
          echo "✅ '${{ inputs.step }}' completed successfully in ${duration}s"
          status="success"
        else
          echo "❌ '${{ inputs.step }}' failed with exit code $exit_code after ${duration}s"
          status="failure"
        fi
        
        echo "📡 Sending data to New Relic..."

        # Send metrics to New Relic (don't fail the step if this fails)
        curl -X POST "https://insights-collector.newrelic.com/v1/accounts/${NEW_RELIC_ACCOUNT_ID}/events" \
          -H "Content-Type: application/json" \
          -H "X-Insert-Key: ${NEW_RELIC_INSERT_KEY}" \
          -d "[{
            \"eventType\": \"GitHubActionsCI\",
            \"repository\": \"${GITHUB_REPOSITORY}\",
            \"workflow\": \"${GITHUB_WORKFLOW}\",
            \"job\": \"${GITHUB_JOB}\",
            \"step\": \"${{ inputs.step }}\",
            \"duration\": ${duration},
            \"status\": \"${status}\",
            \"exit_code\": ${exit_code},
            \"run_id\": \"${GITHUB_RUN_ID}\",
            \"timestamp\": \"${timestamp}\",
            \"actor\": \"${GITHUB_ACTOR}\",
            \"ref\": \"${GITHUB_REF}\",
            \"sha\": \"${GITHUB_SHA}\",
            \"event_name\": \"${GITHUB_EVENT_NAME}\",
            \"head_ref\": \"${GITHUB_HEAD_REF}\",
            \"base_ref\": \"${GITHUB_BASE_REF}\",
            \"pr_number\": \"${pr_number}\",
            \"commit_message\": \"${commit_message}\"
          }]" || echo "⚠️ Failed to send metrics to New Relic (non-fatal)"
        
        # Exit with the original command's exit code
        exit $exit_code