name: GitHub Workflow Timing Collector

on:
  workflow_run:
    workflows: ["Rust CI"] # <-- List the workflows you want to monitor
    types:
      - completed

permissions:
  contents: read
  actions: read

env:
  NEW_RELIC_INSERT_KEY: ${{ secrets.NEW_RELIC_INSERT_KEY }}
  NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
  REPO: ${{ github.repository }}
  WORKFLOW_NAME: ci.yml

jobs:
  collect_timings:
    name: Collect and Send Workflow Timings
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Latest Workflow Run ID
        run: |
          set -e
          echo "Starting to fetch latest completed workflow run ID for workflow: $WORKFLOW_NAME"

          echo "Fetching latest runs JSON..."
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/$REPO/actions/workflows/$WORKFLOW_NAME/runs?status=completed&per_page=1" -o latest_runs.json

          echo "Contents of latest_runs.json:"
          cat latest_runs.json

          latest_run_id=$(jq -r '.workflow_runs[0].id' latest_runs.json)

          echo "Latest run ID: $latest_run_id"
          echo "LATEST_RUN_ID=$latest_run_id" >> $GITHUB_ENV

          echo "Finished fetching latest workflow run ID."

      - name: Fetch Jobs and Steps
        run: |
          set -e
          echo "Starting to fetch jobs and steps for run ID: $LATEST_RUN_ID"

          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/$REPO/actions/runs/$LATEST_RUN_ID/jobs" \
               -o jobs.json

          echo "Contents of jobs.json:"
          cat jobs.json

          echo "Finished fetching jobs and steps."

      - name: Upload jobs.json Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jobs-json
          path: jobs.json

      - name: Format Jobs and Steps
        run: |
          set -e
          echo "Starting to format jobs.json..."
          bash .github/scripts/format-jobs.sh jobs.json $LATEST_RUN_ID "$REPO" "$WORKFLOW_NAME"

          echo "Contents of formatted_jobs.json:"
          cat formatted_jobs.json

          echo "Finished formatting jobs and steps."

      - name: Upload formatted_jobs.json Artifact
        uses: actions/upload-artifact@v4
        with:
          name: formatted-jobs-json
          path: formatted_jobs.json

      - name: Send Timings to New Relic
        run: |
          set -e
          echo "Starting to send timing data to New Relic..."

          data=$(jq -c '[.[]]' formatted_jobs.json)

          curl -X POST "https://insights-collector.newrelic.com/v1/accounts/${{ secrets.NEW_RELIC_ACCOUNT_ID }}/events" \
            -H "Content-Type: application/json" \
            -H "X-Insert-Key: ${{ secrets.NEW_RELIC_INSERT_KEY }}" \
            -d "[
                  {
                    \"eventType\": \"GitHubWorkflowTiming\",
                    \"timestamp\": $(date +%s),
                    \"data\": $data
                  }
                ]"

          echo "Finished sending timing data to New Relic."